#!/bin/bash

# fifo.sh -- Sets up initial Archlinux environment on the specified
# device.
#
# Usage: fifo.sh <DEV> <WIFI_SSID> <WIFI_PASS> 
#
# Copyright (c) 2017 J.B. Freels <jbfreels@me.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -exu

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

DEV=$1
WIFI_SSID=$2
WIFI_PASS=$3

cd $(mktemp -d)

function welcome () {
  clear
  echo -e "${Bold}Raspberri Pi Archlinux Ultimate Install${White}"
}

function choose_editor () {

}

function configure_hostname () {
  read -p "Hostname (archlinux): " host_name
  echo "$host_name" > root/etc/hostname
}

function umountboot {
    umount boot || true
    umount root || true
}

# RPi1/Zero/W (armv6h):
archlinux=/tmp/ArchLinuxARM-rpi-latest.tar.gz
url=http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz

# RPi2 (armv7h):
# archlinux=/tmp/ArchLinuxARM-rpi-2-latest.tar.gz
# url=http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz

curl -L -o $archlinux -z $archlinux $url
parted -s $DEV mklabel msdos
parted -s $DEV mkpart primary fat32 1 128
parted -s $DEV mkpart primary ext4 128 -- -1
mkfs.vfat ${DEV}1
mkfs.ext4 -F ${DEV}2
mkdir -p boot

mount ${DEV}1 boot
trap umountboot EXIT
mkdir -p root
mount ${DEV}2 root

bsdtar -xpf $archlinux -C root
sync
mv root/boot/* boot

cat << EOF >> root/etc/systemd/network/wlan0.network
[Match]
Name=wlan0

[Network]
DHCP=yes
EOF

wpa_passphrase "${WIFI_SSID}" "${WIFI_PASS}" > root/etc/wpa_supplicant/wpa_supplicant-wlan0.conf

ln -s \
   /usr/lib/systemd/system/wpa_supplicant@.service \
   root/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlan0.service
